homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 59
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

config:

octoprint:
  host: 192.168.1.185:5000
  api_key: !secret octoprint_api_key

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret pushbullet_api_key

recorder:
  db_url: mysql://hass:hasspi@localhost/hass

panel_iframe:
  octoprint:
    title: Octoprint
    icon: mdi:printer-3d
    url: http://home.kariudo.com:5000
  router:
    title: Router
    icon: mdi:router-wireless
    url: https://www.linksyssmartwifi.com 
  dakboard:
    title: DAKboard
    icon: mdi:gauge
    url: https://dakboard.com

input_select:
  livingroomharmony:
    name: Harmony Activity
    options:
     - PowerOff
     - Watch TV
     - Watch Nexus Player
     - Watch Plex
     - Listen to Music
     - Play a Game
    initial: PowerOff
    icon: mdi:remote
  scene_livingroom:
    name: Living Room Scene
    options:
      - Select
      - Concentrate
      - Energize
      - Reading
      - Relax
      - 'OFF'
    initial: 'Select'

# Enables the frontend
frontend:

http:
  api_password: !secret api_pass

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors
sensor:
  - platform: plex
    host: 192.168.1.2
  - platform: wunderground
    api_key: !secret wunder_key
    monitored_conditions:
      - temp_f
      - weather
  - platform: fastdotcom
  - platform: rest
    resource: !secret lizard1_feed
    value_template: '{{ value_json.feeds[0].field1 }}'
    name: Lizard 1t
    unit_of_measurement: '°F'
  - platform: rest
    resource: !secret lizard1_feed
    value_template: '{{ value_json.feeds[0].field2 }}'
    name: Lizard 1h
    unit_of_measurement: '%'
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage
  - platform: template
    sensors:
      octoprint_bed_c:
        entity_id:
          - sensor.octoprint_actual_bed_temp
        unit_of_measurement: '°C'
        value_template: '{{ ((float(states("sensor.octoprint_actual_bed_temp")) - 32) * float(5/9)) | round(1) }}' 

#shell_command:
#  turn_off_HACHIGAMI: bash ~/.scripts/turnOffHachigami.sh

switch:
  - platform: wake_on_lan
    mac_address: "C8-60-00-BF-99-35"
    name: "Hachigami"
    host: 192.168.1.2
#    turn_off:
#      service: shell_command.turn_off_HACHIGAMI
  - platform: template
    switches:
      tv:
        value_template: "{% if is_state('remote.living_room', 'on') %}on{% else %}off{% endif %}"
        turn_on:
          service: remote.turn_on
          entity_id: remote.living_room
          data:
            activity: Watch Plex
        turn_off:
          service: remote.turn_off
          entity_id: remote.living_room

# Text to speech
tts:
  platform: google

mqtt:
  broker: m13.cloudmqtt.com
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

script: !include scripts.yaml

media_player:
  - platform: cast
  - platform: plex

camera:
  - platform: mjpeg
    name: Bedroom
    mjpeg_url: http://192.168.1.117/video/mjpg.cgi
    username: admin
    password: !secret bedroom_camera_password
  - platform: mjpeg
    name: Living Room
    mjpeg_url: http://127.0.0.1:8081/

device_tracker:
  - platform: owntracks
  
zone:
  name: Square 9
  latitude: 41.306373
  longitude: -72.925486
  radius: 200
  icon: mdi:domain

zone 2:
  name: Charles River
  latitude: 41.3054537
  longitude: -72.9367557
  radius: 200
  icon: mdi:flask

zone 4:
  name: Roast Meat Hill Road
  latitude: 41.382637
  longitude: -72.551857
  radius: 200
  icon: mdi:duck

# Override home zone
zone 3:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 200
  icon: mdi:home

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.182

group: !include groups.yaml

device_sun_light_trigger:
  light_group: group.living_room_lights
  light_profile: relax
  device_group: group.all_devices

automation: !include automations.yaml

scene: !include scene.yaml
